name: Publish

on:
  push:
    tags:
      - v*

# Set the default shell to use bash with -eo pipefail.
# This doesn't happen by default, which can create some confusing and
# dangerous errors... See https://github.com/actions/runner/issues/353
defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail {0}

jobs:
  publish_tag:
    name: Publish Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Set Version
        run: npm version --no-git-tag-version "${{ github.ref_name }}"
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
